import React, { useState, useEffect } from 'react';
import { Activity, RefreshCw, Zap, ShieldCheck, DollarSign, Clock, Search, ArrowUpRight, Download, FileText } from 'lucide-react';
import { BlockchainEvent, UsageLog } from '../types';

export const IndexerLogView: React.FC = () => {
  const [events, setEvents] = useState<BlockchainEvent[]>([]);
  const [usageLogs, setUsageLogs] = useState<UsageLog[]>([]);
  const [tab, setTab] = useState<'events' | 'usage'>('events');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchIndexerData();
    const interval = setInterval(fetchIndexerData, 3000);
    return () => clearInterval(interval);
  }, []);

  const downloadLogReceipt = (log: UsageLog) => {
    const recId = `REC-X402-${log.id.toUpperCase()}`;
    const timestamp = new Date(log.timestamp).toUTCString();
    const payer = log.clientAddress || '0xF1b0821A87D439811A1B4365C8343f14A41010F3';
    const payloadHash = log.payloadHash || '0xa81c4e9281f23b4567890abcdef1234567890abc';
    const status = log.status.toUpperCase();
    const durationMs = log.durationMs;

    const canvas = document.createElement('canvas');
    canvas.width = 900;
    canvas.height = 1000;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Background Gradient
    const bgGrad = ctx.createLinearGradient(0, 0, 900, 1000);
    bgGrad.addColorStop(0, '#090a15');
    bgGrad.addColorStop(0.5, '#0f1228');
    bgGrad.addColorStop(1, '#05060d');
    ctx.fillStyle = bgGrad;
    ctx.fillRect(0, 0, 900, 1000);

    // Outer Glow Border
    ctx.strokeStyle = '#6366f1';
    ctx.lineWidth = 4;
    ctx.strokeRect(20, 20, 860, 960);

    // Decorative inner border
    ctx.strokeStyle = 'rgba(99, 102, 241, 0.25)';
    ctx.lineWidth = 1;
    ctx.strokeRect(30, 30, 840, 940);

    // Header Banner Box
    ctx.fillStyle = 'rgba(30, 27, 75, 0.7)';
    ctx.fillRect(50, 50, 800, 120);
    ctx.strokeStyle = 'rgba(99, 102, 241, 0.5)';
    ctx.strokeRect(50, 50, 800, 120);

    // Header Content
    ctx.fillStyle = '#a5b4fc';
    ctx.font = 'bold 15px monospace';
    ctx.fillText('x402 MICROPAYMENT INDEXER LOG', 70, 85);

    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 26px sans-serif';
    ctx.fillText('TRANSACTION & USAGE RECEIPT', 70, 120);

    ctx.fillStyle = '#818cf8';
    ctx.font = '13px monospace';
    ctx.fillText(`TELEMETRY LOG ID: ${recId}`, 70, 146);

    // Status Badge
    ctx.fillStyle = status === 'SETTLED' ? '#064e3b' : '#312e81';
    ctx.fillRect(570, 75, 250, 48);
    ctx.strokeStyle = status === 'SETTLED' ? '#10b981' : '#6366f1';
    ctx.lineWidth = 1.5;
    ctx.strokeRect(570, 75, 250, 48);

    ctx.fillStyle = status === 'SETTLED' ? '#34d399' : '#a5b4fc';
    ctx.font = 'bold 14px monospace';
    ctx.fillText(`✓ STATUS: ${status}`, 590, 105);

    // Details Grid
    let y = 220;
    const drawRow = (label: string, val: string, isHighlight = false) => {
      ctx.fillStyle = '#94a3b8';
      ctx.font = 'bold 13px monospace';
      ctx.fillText(label, 70, y);

      ctx.fillStyle = isHighlight ? '#34d399' : '#f8fafc';
      ctx.font = isHighlight ? 'bold 14px monospace' : '13px monospace';
      ctx.fillText(val, 320, y);

      // Divider line
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.08)';
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(70, y + 12);
      ctx.lineTo(830, y + 12);
      ctx.stroke();

      y += 50;
    };

    drawRow('SETTLEMENT STATUS:', status === 'SETTLED' ? 'HTTP 200 OK — SETTLED & INDEXED' : status, true);
    drawRow('CLIENT WALLET:', payer);
    drawRow('NETWORK:', 'Base L2 (Chain ID: 8453)');
    drawRow('ESCROW CONTRACT:', '0x34a8e2e2838cf48efd1163ed82e88258c7e9f3b1');
    drawRow('AMOUNT CHARGED:', '$0.01 USD (3,000,000,000,000 Wei)', true);
    drawRow('LATENCY / DURATION:', `${durationMs} ms`);
    drawRow('TIMESTAMP:', timestamp);

    // Cryptographic Proof Box
    y += 15;
    ctx.fillStyle = 'rgba(15, 23, 42, 0.85)';
    ctx.fillRect(50, y, 800, 180);
    ctx.strokeStyle = 'rgba(99, 102, 241, 0.4)';
    ctx.strokeRect(50, y, 800, 180);

    ctx.fillStyle = '#fbbf24';
    ctx.font = 'bold 14px monospace';
    ctx.fillText('TELEMETRY PROOF & PAYLOAD HASH', 70, y + 40);

    ctx.fillStyle = '#94a3b8';
    ctx.font = '12px monospace';
    ctx.fillText('PAYLOAD KECCAK256 HASH:', 70, y + 80);
    ctx.fillStyle = '#34d399';
    ctx.fillText(payloadHash, 70, y + 105);

    ctx.fillStyle = '#94a3b8';
    ctx.fillText('SMART CONTRACT INDEXER STATUS:', 70, y + 140);
    ctx.fillStyle = '#818cf8';
    ctx.fillText('Immutable Event Stream Registered on Base L2 Indexer', 70, y + 160);

    // Footer
    ctx.fillStyle = '#64748b';
    ctx.font = '12px monospace';
    ctx.fillText('Generated by x402 Real-Time Event Indexer • Base L2 Node', 220, 950);

    // Export Canvas to PNG Image Download
    const imageURI = canvas.toDataURL('image/png');
    const link = document.createElement('a');
    link.href = imageURI;
    link.download = `x402-Receipt-${recId}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const fetchIndexerData = async () => {
    try {
      const [evtRes, usageRes] = await Promise.all([
        fetch('/api/blockchain/events'),
        fetch('/api/blockchain/usage')
      ]);
      const evtData = await evtRes.json();
      const usageData = await usageRes.json();
      setEvents(evtData);
      setUsageLogs(usageData);
    } catch (err) {
      console.error('Failed to update indexer logs:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto pb-12">
      
      {/* Header */}
      <div className="glass-card p-6 sm:p-8 rounded-3xl border border-white/10 space-y-2 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 shadow-xl">
        <div>
          <span className="text-[10px] uppercase tracking-widest text-indigo-300 block font-bold">On-Chain Ledger</span>
          <h1 className="text-2xl sm:text-3xl font-serif-display italic font-bold text-transparent bg-clip-text bg-gradient-to-r from-white via-slate-100 to-indigo-200 flex items-center space-x-3">
            <Activity className="w-6 h-6 text-indigo-400" />
            <span>Transaction History & Audit Logs</span>
          </h1>
          <p className="text-xs text-slate-300 font-code mt-1">Live record of smart contract events, verified payment settlements, and API usage history.</p>
        </div>

        <button
          onClick={fetchIndexerData}
          className="p-3 rounded-2xl bg-slate-900/80 hover:bg-indigo-950/60 border border-slate-700 hover:border-indigo-500/60 text-slate-300 hover:text-white transition-all cursor-pointer shadow-md shrink-0"
        >
          <RefreshCw className="w-4 h-4" />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex space-x-2 font-code text-xs">
        <button
          onClick={() => setTab('events')}
          className={`px-4 py-2.5 rounded-2xl transition-all cursor-pointer ${
            tab === 'events' ? 'bg-indigo-950 text-white border border-indigo-500/60 font-bold shadow-lg shadow-indigo-950/50' : 'glass-card text-slate-400 border border-white/5 hover:text-slate-200'
          }`}
        >
          Contract Events ({events.length})
        </button>
        <button
          onClick={() => setTab('usage')}
          className={`px-4 py-2.5 rounded-2xl transition-all cursor-pointer ${
            tab === 'usage' ? 'bg-indigo-950 text-white border border-indigo-500/60 font-bold shadow-lg shadow-indigo-950/50' : 'glass-card text-slate-400 border border-white/5 hover:text-slate-200'
          }`}
        >
          Payment & API Logs ({usageLogs.length})
        </button>
      </div>

      {/* Tab 1: Blockchain Events List */}
      {tab === 'events' && (
        <div className="glass-card rounded-3xl border border-white/10 p-6 sm:p-8 shadow-xl">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs font-code">
              <thead>
                <tr className="border-b border-white/10 text-slate-400 uppercase text-[10px] tracking-wider font-bold">
                  <th className="pb-4">Block</th>
                  <th className="pb-4">Event Name</th>
                  <th className="pb-4">Transaction Hash</th>
                  <th className="pb-4">Parameters</th>
                  <th className="pb-4">Timestamp</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5 text-slate-200">
                {events.map((evt) => (
                  <tr key={evt.id} className="hover:bg-white/5 transition-colors">
                    <td className="py-3.5 font-bold text-indigo-300 font-mono">#{evt.blockNumber}</td>
                    <td className="py-3.5">
                      <span className="px-2.5 py-1 rounded-xl bg-indigo-950/60 text-indigo-300 font-semibold border border-indigo-700/50 text-[11px]">
                        {evt.eventName}
                      </span>
                    </td>
                    <td className="py-3.5 text-slate-400 font-mono">
                      {evt.txHash.substring(0, 10)}...{evt.txHash.substring(evt.txHash.length - 8)}
                    </td>
                    <td className="py-3.5">
                      <pre className="text-[10px] text-slate-200 bg-slate-950 border border-slate-800 p-2 rounded-xl max-w-xs overflow-x-auto font-mono">
                        {JSON.stringify(evt.parameters)}
                      </pre>
                    </td>
                    <td className="py-3.5 text-slate-400 font-mono">{new Date(evt.timestamp).toLocaleTimeString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Tab 2: Usage Logs */}
      {tab === 'usage' && (
        <div className="glass-card rounded-3xl border border-white/10 p-6 sm:p-8 shadow-xl">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs font-code">
              <thead>
                <tr className="border-b border-white/10 text-slate-400 uppercase text-[10px] tracking-wider font-bold">
                  <th className="pb-4">Usage ID</th>
                  <th className="pb-4">Client</th>
                  <th className="pb-4">Latency</th>
                  <th className="pb-4">Cost (Wei)</th>
                  <th className="pb-4">Payload Keccak256</th>
                  <th className="pb-4">Status</th>
                  <th className="pb-4 text-right">Receipt</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5 text-slate-200">
                {usageLogs.map((log) => (
                  <tr key={log.id} className="hover:bg-white/5 transition-colors">
                    <td className="py-3.5 font-bold text-indigo-300 font-mono">{log.id}</td>
                    <td className="py-3.5 text-slate-400 font-mono">{log.clientAddress.substring(0, 8)}...</td>
                    <td className="py-3.5 text-amber-400 font-bold">{log.durationMs} ms</td>
                    <td className="py-3.5 text-emerald-400 font-bold font-mono">{log.costWei}</td>
                    <td className="py-3.5 text-slate-400 font-mono">{log.payloadHash.substring(0, 12)}...</td>
                    <td className="py-3.5">
                      <span className="px-2.5 py-1 rounded-xl bg-emerald-950/60 text-emerald-300 font-semibold border border-emerald-700/50 text-[11px]">
                        {log.status.toUpperCase()}
                      </span>
                    </td>
                    <td className="py-3.5 text-right">
                      <button
                        onClick={() => downloadLogReceipt(log)}
                        className="px-2.5 py-1 rounded-xl bg-indigo-950 hover:bg-indigo-900 border border-indigo-700/60 text-indigo-300 hover:text-white text-[11px] font-code font-bold inline-flex items-center space-x-1 cursor-pointer transition-all shadow-sm"
                        title="Download Cryptographic x402 PNG Receipt Image"
                      >
                        <Download className="w-3 h-3 text-indigo-400" />
                        <span>PNG Receipt</span>
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

    </div>
  );
};
